### ISSUE TITLE
Add privs

### ISSUE THREAD

**Issue by matt8fr** [everamzah/books#1]
Can you add privs for editing all players book ?

**Comment by taikedz** [comment]
OK - I have added some initial code in a development branch, it still needs fleshing out.

There is a priv called `editor` which will allow players to use the "Magic Pencil"

The Magic Pencil itself is consumable.

Using the Magic Pencil, players can edit a book that exists as a node, if they have the `editor` priv.

This way moderators who do not have `give` still have to exercise restraint ; admins need to explicitly want to edit a book as opposed to just read it (and as such, they do not accidentally re-own the book to themselves)

I'm still working on this, I have been wanting this for a while too Thanks for brining this up.

**Comment by matt8fr** [comment]
Thank you to you, I test it soon.

**Comment by taikedz** [comment]
It is not ready to test yet

**Comment by taikedz** [comment]
This works just about. I still need to be able to remove an item from the user's stack.... but it's functional.

Books can be edited without changing the owner.

Texture is ugly. Needs rotating too.

**Comment by taikedz** [comment]
This feature has been implemented. Closing issue.
