### ISSUE TITLE
minetest.setting error

### ISSUE THREAD

**Issue by mmmsued** [everamzah/books#11]
I found this error in debug.txt

_23 10:54:09: WARNING[Main]: WARNING: minetest.setting_* functions are deprecated.  Use methods on the minetest.settings object. (at ...\mods\books\init.lua:249)_

**Comment by tenplus1** [comment]
Code has been updated and issues fixed: https://forum.minetest.net/viewtopic.php?p=432608#p432608

**Comment by taikedz** [comment]
Based on tenplus1's link, this repo has been updated.

@tenplus1 Do you have a hosted repo ? `notabug` links are now defunct, not sure where to track presently.
