### ISSUE TITLE
Pencil name may be misleading

### ISSUE THREAD

**Issue by mgl512** [everamzah/books#6]
We've been using the pencil since it's available and I think its name is misleading. Some players craft it because it's "magic". They can't find a use for it, ask about it and are disappointed. It's not expensive to craft but it's a bit annoying to have to answer that it's to edit someone else's book and that it's useless without the editor priv. The pencil could have a better description like "Pencil of editing (editor priv)". Most of our players speak French but they should notice the need of a priv anyway and avoid crafting it before asking.

**Comment by taikedz** [comment]
Hm, I had not considered that interpretation.

I've changed it now to "Admin Pencil" ; if you are needing the version for the official 0.4.15 release use version 1.1.1 ; for those using dev builds, master is corrrect, or use 1.2.2

https://github.com/taikedz/everamzah-books/tags

**Comment by mgl512** [comment]
Thanks. We updated the server. We'll see if regular users stop massively crafting it for no use.

**Comment by taikedz** [comment]
Closing for now. If further change is needed, please re-open
